export enum CustomEvents {
  UNAUTHORIZED,
}
export enum RestEnds {
  UserLogin = "UserLogin/OnUserLoginApp",
  GetTaxList = "Ledger/GetTaxList",
  AddTax = "Ledger/AddTax",
  GetSupplierList = "Ledger/GetSupplierList",
  AddSupplierData = "Ledger/AddSupplierData",
  GetCustomerList = "Ledger/GetCustomerList",
  AddCustomerData = "Ledger/AddCustomerData",
  GetItemList = "Item/GetItemList",
  AddItemData = "Item/AddItemData",
  GetSalesList = "Ledger/GetSalesList",
  AddSalesData = "Ledger/AddSalesData",
  GetPurchaseList = "Ledger/GetPurchaseList",
  AddPurchaseData = "Ledger/AddPurchaseData",
  GetItemGroupList = "ItemGroup/GetItemGroupList",
  GetItemCategoryList = "ItemCategory/GetItemCategoryList",
  AddItemCategoryData = "ItemCategory/AddItemCategoryData",
  GetUnitSimpleList = "Unit/GetUnitSimpleList",
  AddUnitSimpleData = "Unit/AddUnitSimpleData",
  AddItemGroupData = "ItemGroup/AddItemGroupData",
  GetOtherExpenseList = "Ledger/GetOtherExpenseList",
  GetRoundOffLessList = "Ledger/GetRoundOffLessList",
  GetRoundOffAddList = "Ledger/GetRoundOffAddList",
  GetCostCenterList = "CostCenter/GetCostCenterList",
  AddCostCenterData = "CostCenter/AddCostCenterData",
  AddReceivedDiscount = "Ledger/AddReceivedDiscount",
  GetReceivedDiscountList = "Ledger/GetReceivedDiscountList",
  GetPaidDiscountList = "Ledger/GetPaidDiscountList",
  AddPaidDiscount = "Ledger/AddPaidDiscount",
  GetStoreList = "Store/GetStoreList",
  AddStoreData = "Store/AddStoreData",
}
